# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'reset-environment'
description: 'Power Platform Reset Environment'
inputs:
  user-name:
    description: 'Power Platform user name to authenticate with, e.g. myname@my-org.onmicrosoft.com. Setting this input makes user-name and password required; specifying alternate "app-id" credential set of inputs will result in an error.'
    required: false

  password-secret:
    description: 'Power Platform password, required if authenticating with username. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: false

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: 'The client secret to authenticate with. Required if authenticating with app-id.'
    required: false

  tenant-id:
    description: 'Tenant id if using app-id & client secret to authenticate.'
    required: false

  environment-url:
    description: 'URL of Power Platform environment to reset; e.g. "https://test-env.crm.dynamics.com"'
    required: false

  environment:
    description: 'Id or URL of Power Platform environment to reset.'
    required: false

  language:
    description: 'Sets the language used for your environment. Defaults to "English".'
    required: false
    default: 'English'

  currency:
    description: 'Sets the currency used for your environment. Defaults to "USD".'
    required: false
    default: 'USD'

  purpose:
    description: 'Sets the description used to associate the environment with a specific intent.'
    required: false

  templates:
    description: 'Sets Dynamics365 app that needs to be deployed. [passed as comma separated values] e.g : -tm "D365_Sample, D365_Sales"'
    required: false

  override-domain-name:
    description: 'Check to override the domain name while resetting the instance.'
    required: false
    default: 'false'

  domain-name:
    description: 'The domain name is part of the environment URL. If you enter a domain name that is already in use, then the task appends a numeric value to the domain name, starting with 0 and sets the environment URL. For example - If the domain name contoso is already in use, then the environment URL will be updated to https://{contoso}0.crm.dynamics.com.'
    required: false

  override-friendly-name:
    description: 'Check to override the friendly name of the environment while resetting the instance.'
    required: false
    default: 'false'

  friendly-name:
    description: 'Sets the name of the environment.'
    required: false

runs:
  using: 'node12'
  main: '../dist/actions/reset-environment/index.js'

