# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'reset-environment'
description: 'Power Platform Reset Environment'
inputs:
  user-name:
    description: 'Power Platform user name, e.g. myname@my-org.onmicrosoft.com'
    required: true

  password-secret:
    description: 'Power Platform password. Do not checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: true

  environment-url:
    description: 'URL of Power Platform environment to reset; e.g. "https://test-env.crm.dynamics.com"'
    required: true

runs:
  using: 'node12'
  main: '../dist/actions/reset-environment/index.js'

