# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'update-solution-version'
description: 'Power Platform Update Solution Version'
inputs:
  build-version:
    description: 'Build version for solution'
    required: false

  revision-version:
    description: 'Revision version for solution'
    required: false

  patch-version:
    description: 'Patch version for solution'
    required: false

  strategy:
    description: 'Strategy to update patch version for Solution.xml file: "gittags", "filetracking" or "solution"'
    required: false

  tracker-file:
    description: 'Name of Tracker CSV file to be used when using filetracking as a strategy. Default value is ControlsStateVersionInfo.csv'
    required: false

runs:
  using: 'node16'
  main: '../dist/actions/update-solution-version/index.js'
  # main: '../out/actions/update-solution-version/index.js'
