# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'upgrade-solution'
description: 'Power Platform Upgrade Solution'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  user-name:
    description: 'Power Platform user name, e.g. myname@my-org.onmicrosoft.com'
    required: true

  password-secret:
    description: 'Power Platform password. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: true

  solution-name:
    description: 'Name of solution to upgrade'
    required: true

  async:
    description: 'Upgrades solution asynchronously'
    required: false

  max-async-wait-time:
    description: 'Max asynchronous wait time in minutes. Default value is 60 mintues'
    required: false

runs:
  using: 'node12'
  main: '../dist/actions/upgrade-solution/index.js'
  # main: '../out/actions/upgrade-solution/index.js'
