# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'assign-group'
description: 'Assign group to a target Power Platform environment with specified security role'
inputs:
  user-name:
      description: 'Power Platform user name to authenticate with, e.g. myname@my-org.onmicrosoft.com. Setting this input makes user-name and password required; specifying alternate "app-id" credential set of inputs will result in an error.'
      required: false

  password-secret:
    description: 'Power Platform password, required if authenticating with username. Do NOT check in password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: false

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: 'The client secret to authenticate with. Required if authenticating with app-id.'
    required: false

  tenant-id:
    description: 'Tenant id if using app-id & client secret to authenticate.'
    required: false

  environment:
    description: 'Id or URL of Power Platform environment to assign user to.'
    required: true

  group:
    description: 'AAD object id of group to assign to target environment.'
    required: true

  group-name:
    description: 'Name of group/team that will created in Dataverse.'
    required: true

  role:
    description: 'Security role name or id to assign to the group.'
    required: true

  team-type:
    description: 'Type of team. [Owner|Access|AadSecurityGroup|AadOfficeGroup]'
    required: true

  membership-type:
    description: 'Team membership type. [MembersAndGuests|Members|Owners|Guests]'
    required: true

  business-unit:
    description: 'ID of business unit to associate application group with.'
    required: false

runs:
  using: 'node16'
  main: '../dist/actions/assign-group/index.js'
