# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'unpack-solution'
description: 'Power Platform Unpack Solution'
inputs:
  solution-file:
    description: 'Path/filename of the local solution zip file'
    required: true

  solution-folder:
    description: 'Target folder into which to unpack the solution.zip contents'
    required: true

  solution-type:
    description: 'Solution type to export as: "Unmanaged", "Managed" or "Both"'
    required: false
    default: 'Unmanaged'

  overwrite-files:
    description: 'OK to overwrite existing files when unpacking a solution.zip'
    required: false
    default: true

runs:
  using: 'node12'
  main: '../dist/actions/unpack-solution/index.js'
  # main: '../out/actions/unpack-solution/index.js'
