# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'unpack-solution'
description: 'Power Platform Unpack Solution'
inputs:
  solution-file:
    description: 'Path/filename of the local solution zip file'
    required: true

  solution-folder:
    description: 'Target folder into which to unpack the solution.zip contents'
    required: true

  solution-type:
    description: 'Solution type to unpack: "Unmanaged", "Managed" or "Both"'
    required: false
    default: 'Unmanaged'

  overwrite-files:
    description: 'OK to overwrite existing files when unpacking a solution.zip'
    required: false
    default: 'true'

  single-component:
    description: Only perform action on a single component type [WebResource|Plugin|Workflow|None]
    required: false
    default: 'None'

  map-file:
    description: The full path to a mapping xml file from which to read component folders to pack
    required: false

  locale-template:
    description: Generates a template resource file. Valid only on Extract. Possible Values are auto or an LCID/ISO code of the language you wish to export. When Present, this will extract the string resources from the given locale as a neutral .resx. If auto or just the long or short form of the switch is specified the base locale for the solution will be used
    required: false

  localize:
    description: Extract or merge all string resources into .resx files.
    required: false

  use-lcid:
    description: "Use LCID's (1033) rather than ISO codes (en-US) for language files"
    required: false
    default: 'false'

  use-unmanaged-file-for-missing-managed:
    description: Use the same XML source file when packaging for Managed and only Unmanaged XML file is found; applies to AppModuleSiteMap, AppModuleMap, FormXml files
    required: false
    default: 'false'

  disable-plugin-remap:
    description: Disabled plugin fully qualified type name remaping
    required: false
    default: 'false'

  process-canvas-apps:
    description: (Preview) While processing the solution, unpack any Canvas apps .msapp file into its YAML source format
    required: false

runs:
  using: 'node16'
  main: '../dist/actions/unpack-solution/index.js'
  # main: '../out/actions/unpack-solution/index.js'
