# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'import-solution'
description: 'Power Platform Import Solution'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  user-name:
    description: 'Power Platform user name to authenticate with, e.g. myname@my-org.onmicrosoft.com. Setting this input makes user-name and password required; specifying alternate "app-id" credential set of inputs will result in an error.'
    required: false

  password-secret:
    description: 'Power Platform password, required if authenticating with username. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: false

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: 'The client secret to authenticate with. Required if authenticating with app-id.'
    required: false

  tenant-id:
    description: 'Tenant id if using app-id & client secret to authenticate.'
    required: false

  cloud:
    description: 'Cloud instance to authenticate with. Default: Public. See "pac auth create help" for valid cloud instance names'
    required: false
    default: 'Public'

  solution-file:
    description: 'Path/filename of solution zip file to be imported. Can be absolute or relative to working-directory.'
    required: true

  activate-plugins:
    description: 'Activate plug-ins and workflows on the solution.'
    required: false
    default: 'true'

  force-overwrite:
    description: 'Force an overwrite of unmanaged customizations.'
    required: false
    default: 'true'

  skip-dependency-check:
    description: 'Skip dependency check against dependencies flagged as product update.'
    required: false
    default: 'false'

  import-as-holding:
    description: 'Import the solution as a holding solution.'
    required: false
    default: 'false'

  stage-and-upgrade:
    description: 'Import the managed solution and immediately apply it as an upgrade.'
    required: false
    default: 'false'

  publish-changes:
    description: 'Publish your changes upon a successful import.'
    required: false
    default: 'false'

  working-directory:
    description: 'Working directory; default: root of repository.'
    required: false

  run-asynchronously:
    description: 'Imports solution asynchronously.'
    required: false
    default: 'false'

  use-deployment-settings-file:
    description: 'Use deployment settings file.'
    required: false
    default: 'false'

  deployment-settings-file:
    description: 'Specify the path and file name of the deployment settings file.'
    required: false

  max-async-wait-time:
    description: 'Maximum wait time in minutes for asynchronous Import; default is 60 min (1 hr).'
    required: false
    default: '60'

  convert-to-managed:
    description: 'Specify whether to import as a Managed solution.'
    required: false
    default: 'false'

  skip-lower-version:
    description: 'Skip solution import if same or higher version is present in current environment.'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: '../dist/actions/import-solution/index.js'
  # main: '../out/actions/import-solution/index.js'
