# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'pack-solution'
description: 'Power Platform Pack Solution'
inputs:
  solution-file:
    description: 'Target Path/filename of the local solution file'
    required: true

  solution-folder:
    description: 'Folder into which to pack the solution contents'
    required: true

  solution-type:
    description: 'Solution type to pack as: "Unmanaged", "Managed" or "Both"'
    required: false
    default: 'Unmanaged'

runs:
  using: 'node12'
  main: '../dist/actions/pack-solution/index.js'
  # main: '../out/actions/pack-solution/index.js'
