# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'export-solution'
description: 'Power Platform Export Solution'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: true

  user-name:
    description: 'Power Platform user name, e.g. myname@my-org.onmicrosoft.com'
    required: true

  password-secret:
    description: 'Power Platform password. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: true

  solution-name:
    description: 'Name of solution to export'
    required: true

  solution-version:
    description: 'Version of solution to export'
    required: false

  solution-output-file:
    description: 'Path/filename where to place the exported solution zip file. Can be absolute or relative to working-directory'
    required: true

  managed:
    description: 'Export as managed solution; default is to export as unmanaged solution'
    required: false

  working-directory:
    description: 'Working directory; default: root of repository'
    required: false

runs:
  using: 'node12'
  main: '../dist/actions/export-solution/index.js'
  # main: '../out/actions/export-solution/index.js'
