# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
name: 'check-solution'
description: 'Power Platform Check Solution'
inputs:
  environment-url:
    description: 'URL of Power Platform environment to connect with; e.g. "https://test-env.crm.dynamics.com"'
    required: false

  user-name:
    description: 'Power Platform user name to authenticate with, e.g. myname@my-org.onmicrosoft.com. Setting this input makes user-name and password required; specifying alternate "app-id" credential set of inputs will result in an error.'
    required: false

  password-secret:
    description: 'Power Platform password, required if authenticating with username. Do NOT checkin password, instead create a secret and reference it here with: see: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow'
    required: false

  app-id:
    description: 'The application id to authenticate with. Setting this input makes app-id, tenant-id and client-secret required; specifying alternate "username" credential set of inputs will result in an error.'
    required: false

  client-secret:
    description: 'The client secret to authenticate with. Required if authenticating with app-id.'
    required: false

  tenant-id:
    description: 'Tenant id if using app-id & client secret to authenticate.'
    required: false

  cloud:
    description: 'Cloud instance to authenticate with. Default: Public. See "pac auth create help" for valid cloud instance names'
    required: false
    default: 'Public'

  path:
    description: 'Path to a solution zip file to check.'
    required: true

  geo:
    description: 'Which geo location of the PowerPlatform Checker Service to use.  Default value is "UnitedStates".'
    required: false

  rule-level-override:
    description: 'Path to a file containing a JSON array of rules and their levels to override.  Accepted values for OverrideLevel are: Critical, High, Medium, Low, Informational. Example: [{"Id":"meta-remove-dup-reg","OverrideLevel":"Medium"},{"Id":"il-avoid-specialized-update-ops","OverrideLevel":"Medium"}]'
    required: false

  checker-logs-artifact-name:
    description: The name of the artifact folder of which the PowerApps Checker logs will be uploaded.  Default value is \'CheckSolutionLogs\'
    required: false

runs:
  using: 'node12'
  main: '../dist/actions/check-solution/index.js'
  # main: '../out/actions/check-solution/index.js'
