# CI workflow for merges to master
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x

    - name: Build and test
      run: |
        npm i
        npm run ci
      env:
        AZ_DevOps_Read_PAT: ${{ secrets.AZ_DevOps_Read_PAT }}
