# CI workflow for PRs and merges to master
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
      with:
        node-version: 12.x

    - name: Build and test
      run: |
        npm i
        npm run ci
      env:
        AZ_DevOps_Read_PAT: ${{ secrets.AZ_DevOps_Read_PAT }}

    - name: Test who-am-i action
      uses: ./who-am-i
      with:
        environment-url: 'https://davidjenD365-1.crm.dynamics.com'
        user-name: 'davidjen@davidjenD365.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: Test export-solution action
      uses: ./export-solution
      with:
        environment-url: 'https://davidjenD365-1.crm.dynamics.com'
        user-name: 'davidjen@davidjenD365.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: emptySolution
        solution-output-file: 'solution1.zip'
        working-directory: 'out/CI'

    - name: Test unpack-solution action
      uses: ./unpack-solution
      with:
        solution-file: 'out/CI/solution1.zip'
        solution-folder: 'out/CI/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true
