# Actions workflow for merges to main
name: rolling-instance-actions

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  push:
    branches: [ main ]

jobs:
  instance-actions:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      WF_USERNAME: davidjen@ppdevtools.onmicrosoft.com
      WF_APPID: 8a7729e0-2b71-4919-a89a-c789d0a9720a
      WF_TENANT_ID: 3041a058-5110-495a-a575-b2a5571d9eac

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Test create-source-environment action with appId-clientSecret
      uses: ./create-environment
      id: create-source-environment
      with:
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}
        name: sourceEnvironment
        type: Sandbox
        region: unitedstates
        domain: test-source

    - name: Test create-target-environment action with username/password
      uses: ./create-environment
      id: create-target-environment
      with:
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        name: targetEnvironment
        type: Sandbox
        region: unitedstates
        domain: test-target

    - name: Test who-am-i action with username/password
      uses: ./who-am-i
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test who-am-i action with appId-clientSecret
      uses: ./who-am-i
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}

    - name: Test pack-solution action
      uses: ./pack-solution
      with:
        solution-folder: 'src/test/data/emptySolution'
        solution-file: 'out/CI/emptySolution.zip'
        solution-type: 'Unmanaged'

    - name: Test import-solution action with username/password
      uses: ./import-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        solution-file: 'out/CI/emptySolution.zip'
        force-overwrite: true
        run-asynchronously: true

    - name: Test export-solution action with appId-clientSecret
      uses: ./export-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}
        solution-name: emptySolution
        solution-output-file: 'solution1.zip'
        working-directory: 'out/CI'
        run-asynchronously: true

    - name: Test unpack-solution action
      uses: ./unpack-solution
      with:
        solution-file: 'out/CI/solution1.zip'
        solution-folder: 'out/CI/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Test clone-solution action with username/password
      uses: ./clone-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        solution-name: emptySolution
        target-folder: 'out/CI/cloned'

    - name: Test publish-solution action with appId-clientSecret
      uses: ./publish-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}

    - name: Test copy-environment action with username/password
      uses: ./copy-environment
      with:
        source-url: ${{ steps.create-source-environment.outputs.environment-url }}
        target-url: ${{ steps.create-target-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test backup-environment action with appId-clientSecret
      uses: ./backup-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        backup-label: test-backup-label
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}

    - name: Test reset-environment action with username/password
      uses: ./reset-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test restore-environment action with appId-clientSecret
      uses: ./restore-environment
      with:
        source-url: ${{ steps.create-source-environment.outputs.environment-url }}
        target-url: ${{ steps.create-target-environment.outputs.environment-url }}
        selected-backup: latest
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}

    - name: Test delete-source-environment action with appId-clientSecret
      uses: ./delete-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test delete-target-environment action with username/password
      uses: ./delete-environment
      with:
        environment-url: ${{ steps.create-target-environment.outputs.environment-url }}
        app-id: ${{ env.WF_APPID }}
        client-secret: ${{ secrets.CLIENT_SECRET_PPDEVTOOLS }}
        tenant-id: ${{ env.WF_TENANT_ID }}

    - name: Upload pac CLI logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pac-cli-log
        path: ./dist/pac/tools/logs/pac-log.txt
