# Actions workflow for merges to main
name: rolling-instance-actions

on:
  workflow_dispatch:    # allow for manual workflow triggering as needed
  push:
    branches: [ main ]

jobs:
  instance-actions:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1
      WF_USERNAME: davidjen@ppdevtools.onmicrosoft.com

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Test create-source-environment action
      uses: ./create-environment
      id: create-source-environment
      with:
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        name: sourceEnvironment
        type: Sandbox
        region: unitedstates
        domain: test-source

    - name: Test create-target-environment action
      uses: ./create-environment
      id: create-target-environment
      with:
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        name: targetEnvironment
        type: Sandbox
        region: unitedstates
        domain: test-target

    - name: Test who-am-i action
      uses: ./who-am-i
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test pack-solution action
      uses: ./pack-solution
      with:
        solution-folder: 'src/test/data/emptySolution'
        solution-file: 'out/CI/emptySolution.zip'
        solution-type: 'Unmanaged'

    - name: Test import-solution action
      uses: ./import-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        solution-file: 'out/CI/emptySolution.zip'
        force-overwrite: true

    - name: Test export-solution action
      uses: ./export-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        solution-name: emptySolution
        solution-output-file: 'solution1.zip'
        working-directory: 'out/CI'

    - name: Test unpack-solution action
      uses: ./unpack-solution
      with:
        solution-file: 'out/CI/solution1.zip'
        solution-folder: 'out/CI/solution one'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Test clone-solution action
      uses: ./clone-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}
        solution-name: emptySolution
        target-folder: 'out/CI/cloned'

    - name: Test publish-solution action
      uses: ./publish-solution
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test copy-environment action
      uses: ./copy-environment
      with:
        source-url: ${{ steps.create-source-environment.outputs.environment-url }}
        target-url: ${{ steps.create-target-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test backup-environment action
      uses: ./backup-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        backup-label: test-backup-label
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test reset-environment action
      uses: ./reset-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Test delete-source-environment action
      uses: ./delete-environment
      with:
        environment-url: ${{ steps.create-source-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}


    - name: Test delete-target-environment action
      uses: ./delete-environment
      with:
        environment-url: ${{ steps.create-target-environment.outputs.environment-url }}
        user-name: ${{ env.WF_USERNAME }}
        password-secret: ${{ secrets.PASSWORD_PPDEVTOOLS }}

    - name: Upload pac CLI logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pac-cli-log
        path: ./dist/pac/tools/logs/pac-log.txt
